name: Unit Tests

on:
  push:
  pull_request:
  
jobs:
  unit_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2

      # overwrites the python versionin the environment for the testing matrix
      - name: Set Python Version ${{ matrix.python-version }}
        # hacky way to change the python version by temporariliy editing the environment file
        run: |
          sed -i -E 's/(python=)(.*)/\1'${{ matrix.python-version }}'/' ./environment_cpu.yaml
          cat environment_cpu.yaml | grep python
      
      # overwrites the python version in the environment
      - uses: conda-incubator/setup-miniconda@v2
        with:
          # mamba-version: "*"  # does not work reliably atm
          # channels: turagalab/label/dev,turagalab,pytorch,conda-forge,defaults
          channel-priority: strict
          activate-environment: decode_dev_cpu
          environment-file: environment_cpu.yaml
      
      - name: Install backport of importlib_resources
        run: |
          conda install -y importlib_resources
        if: matrix.python-version <= '3.6'

      # Run the specific test
      - name: Run pytest (without big web and graphical output)
        run: |
          pytest -m "not webbig" -m "not plot" decode/test